#!/bin/bash

echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5001 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv1
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5002 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv2
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5003 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv3
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5004 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv4
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5005 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv5
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5006 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv6
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5007 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv7
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5008 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv8
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5009 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv9
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5010 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv10
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5011 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv11
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5012 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv12
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5013 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv13
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5014 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv14
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5015 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv15
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5016 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv16
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5017 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv17
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5018 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv18
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5019 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv19
echo "`/bin/netstat -a -n |grep ESTABLISHED |grep 5020 | grep -v 127.0.0.1 |awk '{print $5}' | cut -d: -f1 | sort`"  >/root/.connected_ligtv20




echo "<html>" >/var/www/html/nejat/stat.html
echo "<body>" >>/var/www/html/nejat/stat.html
echo "<p>Updated on `date`</p>" >>/var/www/html/nejat/stat.html
echo "<p> YAYIN 1  /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv1
i=1
while read line
do
echo "<p> $i - $line </p>">>/var/www/html/nejat/stat.html
let i++
done

echo "<p> YAYIN 2 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv2
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done
echo "<p> YAYIN 3 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv3
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done

echo "<p> YAYIN 4 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv4
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done

echo "<p> YAYIN 5 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv5
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done

echo "<p> YAYIN 6 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv6
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done


echo "<p> YAYIN 7 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv7
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done

echo "<p> YAYIN 8 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv8
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done


echo "<p> YAYIN 9 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv9
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done


echo "<p> YAYIN 10 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv10
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done

echo "<p> YAYIN 11 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv11
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done

echo "<p> YAYIN 12 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv12
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done


echo "<p> YAYIN 13 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv13
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done


echo "<p> YAYIN 14 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv14
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done


echo "<p> YAYIN 15 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv15
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done


echo "<p> YAYIN 16 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv16
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done

echo "<p> YAYIN 17 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv17
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done



echo "<p> YAYIN 18 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv18
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done

echo "<p> YAYIN 19 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv19
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done



echo "<p> YAYIN 20 /BAGLI OLAN KULLANICILAR</p>"  >>/var/www/html/nejat/stat.html
exec<./.connected_ligtv20
i=1
while read line
do
echo "<p> $i -$line </p>">>/var/www/html/nejat/stat.html
let i++
done


echo "<p> statistic of server</p>"  >>/var/www/html/nejat/stat.html
echo "<p> </p>"  >>/var/www/html/nejat/stat.html
echo "<p> Current Upload rate </p>"  >>/var/www/html/nejat/stat.html
echo "<p> `/usr/bin/vnstat -tr -i eth0 |awk '/tx/'` </p>" >>/var/www/html/nejat/stat.html
echo "<p> Daily stat </p>"  >>/var/www/html/nejat/stat.html
echo "<p> `/usr/bin/vnstat -s |awk '/rx/'` </p>" >>/var/www/html/nejat/stat.html
echo "<p> `/usr/bin/vnstat -s |awk '/today/'` </p>" >>/var/www/html/nejat/stat.html

#echo "<form action="restart.php" method="post">  <input type="submit" value="Restart Streaming" /> </form>" >>/var/www/html/nejat/stat.html
echo "<body>" >>/var/www/html/nejat/stat.html
echo "<html>" >>/var/www/html/nejat/stat.html
cp /root/lgstat /var/www/html/nejat/stat.html