#!/bin/bash


if [ "$1" = "stream1" ] ; then

pid=`ps ax |grep vliptv01 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid

elif [ "$1" = "stream2" ] ; then


pid=`ps ax |grep vliptv02 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid

elif [ "$1" = "stream3" ] ; then


pid=`ps ax |grep vliptv03 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid

elif [ "$1" = "stream4" ] ; then


pid=`ps ax |grep vliptv04 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid

elif [ "$1" = "stream5" ] ; then


pid=`ps ax |grep vliptv05 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid


elif [ "$1" = "stream6" ] ; then


pid=`ps ax |grep vliptv06 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid


elif [ "$1" = "stream7" ] ; then


pid=`ps ax |grep vliptv07 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid


elif [ "$1" = "stream8" ] ; then


pid=`ps ax |grep vliptv08 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid


elif [ "$1" = "stream9" ] ; then


pid=`ps ax |grep vliptv09 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid

elif [ "$1" = "stream10" ] ; then


pid=`ps ax |grep vliptv10 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid

elif [ "$1" = "stream11" ] ; then


pid=`ps ax |grep vliptv11 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid

elif [ "$1" = "stream12" ] ; then


pid=`ps ax |grep vliptv12 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid

elif [ "$1" = "stream13" ] ; then


pid=`ps ax |grep vliptv13 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid

elif [ "$1" = "stream14" ] ; then


pid=`ps ax |grep vliptv14 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid


elif [ "$1" = "stream15" ] ; then


pid=`ps ax |grep vliptv15 | grep -v grep| awk '{ print $1 }'`
echo "Killing $pid"
kill -9 $pid





else

echo "Wrong Server ."

fi

