#!/bin/bash
#
server="`mysql -unejat -pnejat1122 iptvdb -e 'select stream_server from stream where id = 1;' | awk '{ printf "%s", $0 }' |awk ' { print substr($0,14) }' | awk '{print $1}'`"
/usr/bin/vliptv01 -I dummy -vvv $server  --sout '#standard{access=http,mux=ts,dst=127.0.0.1:9000}' :http-user-agent=HADICANIM -R -d

server="`mysql -unejat -pnejat1122 iptvdb -e 'select stream_server from stream where id = 2;' | awk '{ printf "%s", $0 }' |awk ' { print substr($0,14) }' | awk '{print $1}'`"
/usr/bin/vliptv02 -I dummy -vvv $server  --sout '#standard{access=http,mux=ts,dst=127.0.0.1:9001}' :http-user-agent=HADICANIM -R -d

server="`mysql -unejat -pnejat1122 iptvdb -e 'select stream_server from stream where id = 3;' | awk '{ printf "%s", $0 }' |awk ' { print substr($0,14) }' | awk '{print $1}'`"
/usr/bin/vliptv03 -I dummy -vvv $server  --sout '#standard{access=http,mux=ts,dst=127.0.0.1:9002}' :http-user-agent=HADICANIM -R -d

server="`mysql -unejat -pnejat1122 iptvdb -e 'select stream_server from stream where id = 4;' | awk '{ printf "%s", $0 }' |awk ' { print substr($0,14) }' | awk '{print $1}'`"
/usr/bin/vliptv04 -I dummy -vvv $server  --sout '#standard{access=http,mux=ts,dst=127.0.0.1:9003}' :http-user-agent=HADICANIM -R -d

server="`mysql -unejat -pnejat1122 iptvdb -e 'select stream_server from stream where id = 5;' | awk '{ printf "%s", $0 }' |awk ' { print substr($0,14) }' | awk '{print $1}'`"
/usr/bin/vliptv05 -I dummy -vvv $server  --sout '#standard{access=http,mux=ts,dst=127.0.0.1:9004}' :http-user-agent=HADICANIM -R -d

server="`mysql -unejat -pnejat1122 iptvdb -e 'select stream_server from stream where id = 6;' | awk '{ printf "%s", $0 }' |awk ' { print substr($0,14) }' | awk '{print $1}'`"
/usr/bin/vliptv06 -I dummy -vvv $server  --sout '#standard{access=http,mux=ts,dst=127.0.0.1:9005}' :http-user-agent=HADICANIM -R -d

server="`mysql -unejat -pnejat1122 iptvdb -e 'select stream_server from stream where id = 7;' | awk '{ printf "%s", $0 }' |awk ' { print substr($0,14) }' | awk '{print $1}'`"
/usr/bin/vliptv07 -I dummy -vvv $server  --sout '#standard{access=http,mux=ts,dst=127.0.0.1:9006}' :http-user-agent=HADICANIM -R -d